env:
  es6: true
  node: true
  jest: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
ignorePatterns:
  - 'node_modules/'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: off
  require-atomic-updates: off
globals:
  jasmine: true
  window: true
  fetch: true
  Headers: true
  document: true
  Cookies: true
  nearConfig: true
  nearlib: true
  near: true
  walletAccount: true
  contract: true
  testSettings: true
  logLn: true
  getProject: true
  monaco: true
  fileTypeForExtension: true
  assert: true
  setupCallback: true
  $: true


